push1=uicontrol('Style','pushbutton',...
    'String','Open image',...
    'Units','Normalized',...
    'Position',[0.05 0.6 0.4 0.3],...
    'Callback',@push1_Callback); 

push2=uicontrol('Style','pushbutton',...
    'String','Use camera',...
    'Units','Normalized',...
    'Position',[0.55 0.6 0.4 0.3],...
    'Callback',@push2_Callback);